#
# Copyright (C) 2024 Antonino Scordino
# Copyright (C) 2024 Souhrud Reddy
#
# SPDX-License-Identifier: Apache-2.0
#

name: Crave Builder
on:
  workflow_dispatch:

jobs:
  prepare:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: build
      id: proj-variables
      run: |
          sudo apt-get install repo
          sudo apt-get install git
          sudo apt-get update
          sudo apt-get upgrade
          repo init -u https://github.com/LineageOS/android.git -b lineage-21.0
          repo sync
          git config --global user.email "balazs.kokai.builds@gmail.com"
          git config --global user.name "balazskokai"
          git clone https://github.com/dev-harsh1998/android_device_xiaomi_nabu -b lineage-21 device/xiaomi/nabu
          git clone https://github.com/dev-harsh1998/android_kernel_xiaomi_nabu -b lineage-21 kernel/xiaomi/nabu
          git clone https://github.com/balazskokai/android_vendor_xiaomi_nabu -b lineage-21
          source build/envsetup.sh
          lunch lineageos_nabu-userdebug
          make clean
          make apache-xml
          make ims-common
          brunch nabu
          



        
